admin:
  servers: 2
  hostname: admin
  box: chef/fedora-20
  boot_timeout: 300
  halt_timeout: 120
api:
  servers: 2
client:
  servers : 1
proxy:
  servers: 2
fulfillment:
  servers: 1
worker:
  servers: 4